### ISSUE TITLE
Document #1114

### ISSUE THREAD

**Issue by phated** [noir-lang/docs#104]
This didn't trigger the workflow (maybe because it was an older PR?) so I'm manually opening.

The UP + new source build workflow stuff in https://github.com/noir-lang/noir/pull/1114 needs to be documented

**Comment by signorecello** [comment]
This is for v0.5.0 @critesjosh, I'll prioritize the ones for v0.4.1

**Comment by critesjosh** [comment]
@phated is this still relevant now that we can install 0.5.0 with `noirup`?

**Comment by Globallager** [comment]
> Would it be sufficient to link to [this section](https://github.com/noir-lang/noir#working-on-this-project) of the noir README as the source of truth so we dont need to maintain it in two places?

Sounds good to me (would be great to get your confirmation too @phated on e.g. if the instructions are planned to stay there).

**Comment by phated** [comment]
I don't believe it will be sufficient to link to the readme because @kevaundray wanted that to move to somewhere shared (possibly the website?). See https://github.com/noir-lang/noir/issues/1199

**Comment by Globallager** [comment]
So the other way round with the docs as the source of truth then?

**Comment by phated** [comment]
> So the other way round with the docs as the source of truth then?

Possibly, but they need to be written in a way that is generic enough for all noir-lang projects to link to. I can take a stab when I have some free time.

**Comment by Globallager** [comment]
We probably don't need the generic version of nix instructions in the docs, as most readers will be reading it just for compiling Nargo (instead of also other repos).

To unblock us from releasing v0.5.1, let's:
1. Copy-paste the [current instructions in _noir-lang/noir_’s README](https://github.com/noir-lang/noir#working-on-this-project) into docs
2. Release v0.5.1
3. Write up a generic version of instructions at some common place later

(Copy-pasting instead of linking for (1) to avoid broken links if we have to move things around during (3).)

@signorecello / @critesjosh grateful if one of you could take (1) on 🙌

**Comment by critesjosh** [comment]
yes will do
